spring.application.name=api-gateway
server.port=${PORT:8970}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false

spring.cloud.gateway.server.webmvc.routes[0].id=Pedidos
spring.cloud.gateway.server.webmvc.routes[0].uri=${PEDIDOS_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/Pedidos/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=Reservas
spring.cloud.gateway.server.webmvc.routes[1].uri=${RESERVAS_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/Reservas/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=Auth
spring.cloud.gateway.server.webmvc.routes[2].uri=${AUTH_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/Auth/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

jwt.secret=${JWT_SECRET:CibertecGrupo12ClaveSecretaJWTParaFirmarTokensDebeSerLargaYSegura2026}
