spring.application.name=Pedidos
server.port=${PORT:8083}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/db_whasheng?serverTimezone=America/Lima}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.upload-dir=uploads
message.global.done=Integracion exitosa!

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false
